### ISSUE TITLE
[question] Browser support?

### ISSUE THREAD

**Issue by dylanmtaylor** [domenic/streams-demo#3]
This is some really cool stuff. I know it's experimental, but how supported in modern browsers is it? It works in Chrome Canary, but will this feature work in Firefox, Opera, Safari, etc. in the near future?

**Comment by domenic** [comment]
Hopefully! You can check out the [blink-dev intent to ship](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/35_QSL1ABTY) where there's a more detailed report on what other vendors are doing with regard to fetch and streams. "Near" future might be stretching it...
